version: "3"
services:
  kojitechsapiserver:
    depends_on:
      - postgresqlserver
    volumes:
      - ./app:/app
      - kojitechsapistaticdata:/vol/web  
    build:
      context: . 
    env_file:
      - app/.env

  proxy:
    image: kojitechs-proxy-to-app:v1.0.01
    environment:
      - APP_HOST=kojitechsapiserver
    depends_on:
      - kojitechsapiserver
    ports:
      - "8000:8000"
    volumes:
      - kojitechsapistaticdata:/vol/static
         
  postgresqlserver:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - app/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - kojitechsapipostgres:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
        - kojitechsapiredis:/data
    entrypoint: redis-server --appendonly yes --port 6379

volumes:
  kojitechsapipostgres:
  kojitechsapiredis: 
  kojitechsapistaticdata: