version: "3"
services:
  kojitechs-kart:
    depends_on:
      - postgres_db
    volumes:
      - ./app:/app
      - static_data_dev:/vol/web   
    build:
      context: . 
    environment:
      - PORT=8000
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    command: >
      sh -c "chmod +x /app/migration.sh &&
             sh /app/migration.sh"

  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - app/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
        - redis_data_dev:/data
    entrypoint: redis-server --appendonly yes --port 6379

volumes:
  postgres_data_dev:
  redis_data_dev: 
  static_data_dev: