# Generated by Django 3.2.16 on 2022-11-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0002_auto_20221114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='schoolappi.course'),
        ),
    ]
