# Generated by Django 4.1.3 on 2022-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolappi", "0004_review_review_user_student_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default=None,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default=None,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
