# Generated by Django 3.2.16 on 2022-11-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0009_rename_number_rating_course_number_of_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('t', 'Terraform'), ('d', 'Docker'), ('k', 'kubernetes'), ('p', 'python')], max_length=1),
        ),
    ]
