# Generated by Django 4.1.3 on 2022-11-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolappi", "0010_alter_course_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                choices=[
                    ("Terraform", "Terraform"),
                    ("Docker", "Docker"),
                    ("Kubernetes", "kubernetes"),
                    ("Python", "python"),
                ],
                max_length=10,
            ),
        ),
    ]
