# Generated by Django 3.2.16 on 2022-11-16 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schoolappi.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0011_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('amount_paid', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to=schoolappi.models.upload_to)),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='schoolappi.student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
