# Generated by Django 3.2.16 on 2022-11-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0012_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
