# Generated by Django 3.2.16 on 2022-11-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0013_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
