# Generated by Django 3.2.16 on 2022-11-17 01:58

from django.db import migrations, models
import schoolappi.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0015_auto_20221117_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, upload_to=schoolappi.models.upload_to),
        ),
    ]
