# Generated by Django 3.2.16 on 2022-11-17 02:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0016_auto_20221117_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='updated_at',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='course_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='schoolappi.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolappi.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line_1',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
