# Generated by Django 3.2.16 on 2022-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0019_alter_payment_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_of_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_balance',
            field=models.FloatField(default=10000, max_length=100),
        ),
    ]
