# Generated by Django 3.2.16 on 2022-11-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0020_auto_20221117_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolappi.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_user', to='schoolappi.student'),
        ),
    ]
