# Generated by Django 3.2.16 on 2022-11-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0021_auto_20221117_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='number_of_payment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_balance',
        ),
    ]
