# Generated by Django 3.2.16 on 2022-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0022_auto_20221117_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_of_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_balance',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
