# Generated by Django 3.2.16 on 2022-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0027_auto_20221117_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course_name',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='not completed', max_length=20),
        ),
    ]
