# Generated by Django 3.2.16 on 2022-11-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0029_student_total_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_balance',
            new_name='current_balance',
        ),
    ]
