# Generated by Django 3.2.16 on 2022-11-17 09:09

from django.db import migrations
import schoolappi.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0030_rename_student_balance_student_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=schoolappi.models.NameField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nick_name',
            field=schoolappi.models.NameField(blank=True, max_length=100, null=True),
        ),
    ]
