# Generated by Django 3.2.16 on 2022-11-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0031_auto_20221117_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
