# Generated by Django 3.2.16 on 2022-11-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolappi', '0032_alter_student_current_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
